- .vscode/extensions.json
- .vscode/settings.json
- haohao.how.code-workspace
- add recommended extensions
- migrate settings.json to .code-workspace
> Add default VS Code settings

- projects/frontend/.eslintrc.cjs
- projects/frontend/package.json
- yarn.lock
The [package](https://github.com/drizzle-team/drizzle-orm/tree/main/eslint-plugin-drizzle) doesn't have that many rules at the moment but covers some good gotchas.
e.g. https://orm.drizzle.team/docs/eslint-plugin#enforce-update-with-where
> Add eslint-plugin-drizzle

- haohao.how.code-workspace
- projects/frontend/.prettierrc
- projects/frontend/.storybook/main.ts
- projects/frontend/package.json
- projects/frontend/src/hooks.client.ts
- projects/frontend/src/hooks.server.ts
- projects/frontend/src/stories/Page.stories.ts
- yarn.lock
- vscode settings:
- code actions on save
- default formatter 
- prettier organize import plugin
> Update prettier settings

- projects/frontend/package.json
- projects/frontend/src/lib/RiveAnimation.svelte
- projects/frontend/src/routes/rive-example/+page.svelte
- projects/frontend/src/stories/RiveAnimation.stories.ts
- yarn.lock
Add a simple component to render a rive animation
> Add rive component / page / story

- moon.yml
- package.json
- projects/frontend/package.json
- yarn.lock
The `link:` protocol stuff is inspired by https://github.com/yarnpkg/berry/issues/889
> Add `yarn doctor` CI check

- haohao.how.code-workspace
- Remove redundant field
- Increase git-commit ruler to 80
> Tweak VS Code formatting settings

- .prototools
This fixes the issue with running tasks inside a project folder.
> Upgrade to moon 1.21.3

- projects/mobile/package.json
- yarn.lock
This fixes the vulnerable `ip` dep.
> Upgrade react-native for security

- projects/mobile/package.json
- yarn.lock
Running `moon run dev-web` now works properly.
> Fix expo web dependencies

- .github/workflows/preview-vercel-frontend.yml
- .github/workflows/production-db-migrate.yml
- .github/workflows/production-vercel-frontend.yml
- .moon/tasks/tag-vercel.yml
- projects/frontend/moon.yml
- projects/frontend/package.json
- projects/mobile/.gitignore
- projects/mobile/moon.yml
- projects/mobile/package.json
- projects/mobile/vercel.json
- yarn.lock
This replaces the frontend, switching to expo for web instead of sveltekit.
> Add vercel deployment for mobile

- .github/workflows/expo.yml
- projects/frontend/app.json
- projects/frontend/eas.json
- projects/frontend/moon.yml
- projects/frontend/package.json
- yarn.lock
This automatically deploys `frontend` via Expo EAS.
> Add EAS update

- .github/workflows/expo-eas-build.yml
I think I need to make preview builds for internal distribution.
> Add EAS build profile parameter

- projects/frontend/moon.yml
This follows the getting started docs https://docs.expo.dev/eas-update/getting-started/
> Use latest eas-cli

- projects/frontend/app.json
- projects/frontend/package.json
- projects/frontend/public/.well-known/apple-app-site-association
- projects/frontend/public/.well-known/assetlinks.json
- projects/frontend/src/AppEntry.js
- projects/frontend/src/app/index.js
- projects/frontend/src/app/learn/index.js
- projects/frontend/src/main.js
- yarn.lock
- Add a second page at `/learn`
- Setup AASA and Assetlinks for universal links
> Swap to expo-router

- projects/frontend/public/.well-known/apple-app-site-association
https://branch.io/resources/aasa-validator/ reported it as a problem.
> Make AASA valid JSON

- projects/frontend/src/app/_layout.js
It still doesn't work properly on web, but it's a start.
> Fix white background boxing on mobile

- projects/frontend/app.json
- projects/frontend/package.json
- projects/frontend/src/app/index.js
- projects/frontend/src/app/learn/index.js
- projects/frontend/src/components/RootView.tsx
- projects/frontend/src/components/types.ts
- projects/frontend/tsconfig.json
- yarn.lock
Introduces `RootView` that on web sets the body background color. It seems like there should be a more "built-in" way to do this but perhaps not…
> Fix top background color on web

- haohao.how.code-workspace
- projects/frontend/src/app/index.tsx
- projects/frontend/src/app/learn/index.tsx
- projects/frontend/src/components/CircleButton.tsx
…and update all the typescript files in frontend.
> Enable automatic organize imports

- projects/frontend/src/app/_layout.tsx
- projects/frontend/src/app/learn/index.tsx
- Add `Platform.OS` and `Platform.Version`.
- Remove the crash button.
> Tweak Sentry settings

- projects/frontend/src/app/index.tsx
- projects/frontend/src/components/RectButton.tsx
- projects/frontend/src/components/SectionHeaderButton.tsx
> Add RectButton

- projects/frontend/package.json
- projects/frontend/src/app/learn/_layout.tsx
- projects/frontend/src/app/learn/quiz.tsx
- projects/frontend/src/components/FourUpQuiz.tsx
- projects/frontend/src/components/RootView.tsx
- yarn.lock
This uses a nested react navigation stack navigator with custom transition to allow animating through multiple screens, without unmounting the header that shows progress (which is needed for showing an animation).
> Add animated step transition to 4-up quiz

- projects/frontend/src/app/learn/quiz.tsx
- projects/frontend/src/components/FourUpQuiz.tsx
Adds progression through with success tracking.
> Support multiple questions in a quiz

- .prototools
- README.md
Add instructions to the README
> Upgrade Moon

- .moon/tasks/tag-typescript.yml
- moon.yml
- package.json
- projects/emails/package.json
- projects/frontend/package.json
- projects/static/package.json
- tsconfig.json
- yarn.config.cjs
- yarn.lock
- Add Yarn constraints
- Align versions of dependencies across workspaces
- Add root typechecking
- Upgrade Vercel
> Some dependency improvements

- README.md
- yarn.lock
Resolves https://github.com/bradleyayers/haohao.how/security/dependabot/16
> Upgrade tar to 6.2.1

- projects/frontend/tsconfig.json
dist/ was being typechecked locally but it's generated content
> Don't typecheck generate files

- yarn.lock
> Upgrade ws

- projects/frontend/src/app/_layout.tsx
- projects/frontend/src/main.js
- projects/frontend/src/polyfill/crypto.ts
- projects/frontend/src/polyfill/symbolAsyncIterator.ts
Adds a polyfill for `Symbol.asyncIterator`.
> Fix for..await..of on mobile

- projects/frontend/eslint.config.mjs
- projects/frontend/src/components/RectButton.tsx
- projects/frontend/src/components/ReplicacheContext.tsx
- projects/frontend/src/components/replicacheOptions.ts
- projects/frontend/src/util/fsrs.ts
And mess with some replicache debugging code.
> Enable ESLint object-shorthand

- .yarn/patches/hanzi-npm-2.1.5-506390bb41.patch
- projects/frontend/eslint.config.mjs
- projects/frontend/package.json
- projects/frontend/src/app/character/[id].tsx
- projects/frontend/src/app/index.tsx
- projects/frontend/src/app/radical/[id].tsx
- projects/frontend/src/app/word/[id].tsx
- projects/frontend/src/data/generator.ts
- projects/frontend/src/dictionary/characters.ts
- projects/frontend/src/dictionary/hanzi.ts
- projects/frontend/src/dictionary/radicals.ts
- projects/frontend/src/dictionary/words.ts
- projects/frontend/src/typings/hanzi.d.ts
- yarn.lock
- Add HanziJS (but don't use it yet), patch it to work on Hermes.
- Queue skills for a bunch of characters.
- Generate better questions.
> Generate better questions for one-choice

- projects/frontend/src/components/QuizDeck.tsx
- projects/frontend/src/components/QuizDeckOneCorrectPairQuestion.tsx
This fixes the ordering of questions in a quiz, so that when you get one wrong you can move onto another one.
> Allow moving past incorrect answers in a quiz

- projects/api/tsconfig.json
- projects/emails/tsconfig.json
- projects/frontend/tsconfig.json
- projects/static/tsconfig.json
- tsconfig.base.json
- tsconfig.json
Makes it easier to share common config.
> Introduce tsconfig.base

- moon.yml
- projects/frontend/src/components/ReplicacheContext.tsx
- Rename the root moon project to "root" instead of "haohao.how"
- Delete commented out dead code
> Minor clean-ups

- .github/workflows/release.yml
It was missing the sentry auth
> Fix API vercel release

- .github/actions/setup-tools/action.yml
- .github/workflows/ci-daily.yml
- .github/workflows/expo-eas-build.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
This reduces some duplication between workflows
> Use local github action for `setup-tools`

- projects/app/app.json
See https://docs.expo.dev/router/reference/api-routes/
> Add the Expo API route origin config

- .moon/toolchain.yml
- package.json
Hopefully avoids the need to recompile re2 on install.
> Upgrade to Node 22.4

- projects/app/eslint.config.mjs
- projects/app/src/app/api/auth/login/apple+api.ts
It was annoying and TypeScript does a better job
> Remove eqeqeq ESLint rule

- .github/actions/setup-tools/action.yml
Avoid any potential conflicts with prototools
> Only use corepack for pnpm

- .yarn/patches/metro-runtime-npm-0.80.9-3f02d2003d.patch
- package.json
- yarn.lock
See https://github.com/getsentry/sentry-react-native/issues/3860#issuecomment-2214814405
> Fix noise in import cycle in Sentry

- projects/app/src/app/_layout.tsx
- projects/app/src/app/dev/ui.tsx
- projects/app/src/app/index.tsx
- projects/app/src/tamagui.config.ts
- load fonts in the root layout
- make all font sizes consistent
> Add typography ui demo

- projects/app/package.json
- projects/app/src/tamagui.config.ts
- yarn.lock
Solution on https://github.com/tamagui/tamagui/issues/641
> Fix matchMedia warning

- projects/app/src/app/dev/ui.tsx
- projects/app/src/components/AnswerButton.tsx
- projects/app/src/components/QuizDeckOneCorrectPairQuestion.tsx
- projects/app/src/components/RectButton2.tsx
Allow passing throught className
> Fix RectButton2 sizing

- projects/app/src/app/(sidenav)/_layout.tsx
- projects/app/src/app/(sidenav)/index.tsx
- projects/app/src/app/learn/radicals.tsx
- projects/app/src/components/AnswerButton.tsx
- projects/app/src/components/QuizDeckOneCorrectPairQuestion.tsx
- projects/app/src/components/RectButton2.tsx
Add hover states, add radicals side menu.
> Button tweaks

- projects/app/app.config.js
Perhaps this will resolve the `Runtime version mismatch` error in EAS.
> Bump version to 1.9.0

- projects/app/src/app/learn/hsk1.tsx
- projects/app/src/app/learn/radicals.tsx
- projects/app/src/app/learn/reviews.tsx
- projects/app/src/data/generator.ts
- projects/app/src/data/marshal.ts
- projects/app/src/data/query.ts
Fix `indexScanIter` bug that prevented it from every passing the first page.
> Fix upcoming review page.

- projects/app/src/app/_layout.tsx
- projects/app/src/app/learn/radicals.tsx
- projects/app/src/app/learn/reviews.tsx
- projects/app/src/app/login/index.tsx
- Also migrate some usages of RectButton to RectButton2
> Fix Apple sign in button on iOS

- projects/app/package.json
- yarn.lock
Reverts haohao-how/haohaohow#979
> Revert "Update dependency drizzle-orm to ~0.40.0"
