pinyinlylabs/pinyinly

projects/frontend/moon.yml
- Remove `yarn` prefix on commands
- Rename auto-generated `something-dep-1` named tasks
- Make string quoting consistent.
=> Fix quirks in moon.yml

projects/frontend/package.json, yarn.lock
Fixes yarn warning 
```
➤ YN0002: │ button@workspace:projects/frontend doesn't provide @types/node (p01f57), requested by ts-node.
```
=> Add @types/node

.github/workflows/production-db-migrate.yml
The environment variable works locally, but doesn't work in Github Actions for some reason. Trying `--token` instead.
=> Use `--token` instead of `VERCEL_TOKEN`

projects/frontend/src/bin/migrate.ts
Semantic conflict, I merged organise imports PR, then @bradleyayers merged a new file `migrate.ts` that didn't get run through the new prettier config.
=> Organize imports in migrate.ts

.moon/toolchain.yml, .moon/workspace.yml, tsconfig.json
This also turns off project reference syncing and path syncing, I'm not sure if these will be useful—it's a bit hard to evaluate until there is actually more than one TypeScript project.
=> Add root tsconfig.json

.prototools, README.md, package.json, yarn.lock
Previously `@moonrepo/cli` was installed, and when using proto shims for moon it would prefer using the version installed in `node_modules/.bin/moon` (it seems like it uses a heuristic of if a `.moon/` exists).
=> Use moon via proto (properly)

.moon/tasks/tag-chromatic.yml, .moon/tasks/tag-eslint.yml, .moon/tasks/tag-prettier.yml, .moon/tasks/tag-sveltekit.yml, projects/frontend/moon.yml
This utilizes project tags and task inheritence to make it easier to add more projects without the boilerplate of repeating task config. There are now four tags `chromatic`, `eslint`, `prettier`, `sveltekit` and there are corresponding task configs in `.moon/tasks/tag-*.yml` that provide configuration for each.
=> Use moon task inheritence

projects/emails/.gitignore
It's a build artifact so it shouldn't be committed to the repo.
=> Git ignore emails/dist

.github/workflows/expo-eas-build.yml
There are only 15 (iOS) on the free tier, there's no point in wasting them.
=> Do not auto EAS build on push

.github/workflows/expo-eas-update.yml, projects/frontend/moon.yml
It was running `npx sentry-expo-upload-sourcemaps dist` in the wrong directory, so I've migrated it to Moon to avoid the goof.
=> Fix EAS Update sentry source maps upload

projects/frontend/src/app/_layout.tsx
- Don't send reports to Sentry in dev mode.
- Only use `debug` mode in dev mode.
=> Better Sentry dev mode handling

projects/frontend/src/components/FourUpQuiz.tsx, projects/frontend/src/components/SectionHeaderButton.tsx
Weirdly `userSelect: "none"` only works within `StyleSheet.create(…)`, doing it in inline styles on the element doesn't work.
=> Fix warnings for deprecated `selectable`

projects/frontend/app.json, projects/frontend/package.json, projects/frontend/src/components/FourUpQuiz.tsx, yarn.lock
The challenging part here was getting the gradient to not change, but rather be static and revealed gradually. I played around with a few options, initially tried a mask but `MaskedView` only works on mobile (not web). Instead tried the `onLayout` approach which meant the gradient could have an absolute width and then its container have `overflow: hidden` to mask it.
=> Add progress bar streak colors

projects/frontend/app.json
lodash-es was swapped for lodash, so it probably broke things.
=> Bump version to 1.4.0

projects/frontend/eslint.config.mjs, projects/frontend/src/app/index.tsx, projects/frontend/src/app/learn/quiz.tsx
Replace it with `react-native-safe-area-context` instead. This gives more flexibility (e.g. allows using `<LinearGradient>` to the top of the screen.)
=> Remove `SafeAreaView`

.moon/toolchain.yml, README.md, moon.yml, package.json
This fixes an issue with Expo where it was logging warnings:
```
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```
It would output one line for each `_layout.tsx` in the project. The issue only seems to have started in Node.js 22. Another work-around is to convert these files to CommonJS with `require()` and `module.exports =`, but that will create more refactoring burden later. There's a reddit thread about it too https://www.reddit.com/r/expo/comments/1cvhzlr/constantly_getting_a_warning_to_load_an_es_module/
Instead for now downgrading to v21.
Also added instructions for how to change the Node.js version, and reported a bug to Moon for it not respecting ancestor `.prototools` for the Node.js version. …
=> Downgrade Node.js to v21

projects/frontend/.env.test, projects/frontend/src/env.ts
Instead using a sentinel value and swap it out at runtime with the value from the `replicache` package. This makes it less fragile in the case where replicache changes the value of `TEST_LICENSE_KEY`.
=> Remove hard-coded TEST_LICENSE_KEY value

projects/frontend/src/app/index.tsx, projects/frontend/src/app/learn/quiz.tsx, projects/frontend/src/components/QuizDeck.tsx, projects/frontend/src/components/ReplicacheContext.tsx, projects/frontend/src/data/marshal.test.ts, projects/frontend/src/data/marshal.ts, projects/frontend/src/data/migrations/v2.ts, projects/frontend/src/data/model.ts, projects/frontend/src/data/mutators.ts, projects/frontend/src/util/ExpoSQLiteKVStore.ts
- Make mutators use marshaled values (since these are sent over the network and saved in the local DB until flushed).
- Add mutation functions (separate from `r.mutate.*`) with non-marshaled API.
- Remove dynamic date calculation in replicache mutators (mutators should be deterministic so that during rebase they produce the same result).
- Make DB debug logging transaction IDs keyed off the database name (not just the connection).
=> Replicache refactorings/experiments

.moon/tasks/tag-chromatic.yml, .moon/tasks/tag-eslint.yml, .moon/tasks/tag-prettier.yml, .moon/tasks/tag-typescript.yml, .moon/tasks/tag-vercel.yml, README.md, moon.yml, projects/api/moon.yml, projects/emails/moon.yml, projects/frontend/moon.yml, projects/static/moon.yml
- `platform: node` is only needed when the executable is something found in `./node_modules/.bin` and should be run with Node, rather than something on system PATH.
- `command:` string is much more readable than list syntax
- Using `extends:` hurts readability, in most cases it's clearer to just inline things.
=> Clean Moon config

.github/workflows/ci-daily.yml
I realised most were being skipped because moon was only running targets based on changes from the last commit.
=> Run all tests in daily CI

renovate.json
@types/ version ranges are already kept correct with respect to their sibling package via Yarn constraints, so renovate should not try to bump them outside the range.
This should fix @types/react being bumped
=> Don't renovate @types/ beyond range

.github/workflows/pr.yml
I think because `''` was falsy using the `&&` and `||` as a ternary doesn't work so needed to be flipped so that `''` was always last.
=> Fix neon branch name to not include run_attempt

renovate.json
- Swap from `matchManager` to `matchDatasources` so that the regex managers are included.
- Allow automerging any non-major updates.
- Simplify the logic to prevent updating major versions of libraries in package.json.
- Add support for `yarn dlx` while I'm here.
=> Automerge more renovate PRs

.github/workflows/pr.yml, .github/workflows/release.yml, .moon/tasks/tag-vercel.yml, moon.yml, projects/app/moon.yml, projects/static/moon.yml
- Fix PR builds deploying to Vercel production (oops).
- Refactor vercel deployment moon tasks to live be in one place.
- Move `vercel pull` code into the moon task (this simplifies GH actions).
- Disable concurrency for the `main` branch `release` workflow (oops).
- Only deploy if needed (based on moon `--affected`). This should avoid hitting the Vercel deployment 24 hour limit.
=> CI improvements

.github/workflows/expo-eas-build.yml, .moon/tasks/tag-prettier.yml, package.json, projects/app/moon.yml, yarn.lock
- Remove left-over prettier package.json dependency.
- Add `-y` (`--yes`) to all npx commands so they don't hang the first time you run them.
=> Fix npx scripts

.github/workflows/ci-daily.yml
`moon check -u -all` doesn't respect `runInCI`.
=> Fix CI daily workflow

renovate.json
The trailing `\s` in the rule was confusing it with new lines (in the case where there are no arguments to the npx command).
=> Fix renovate for npx

.moon/toolchain.yml, package.json, renovate.json
This should keep moon's toolchain in sync with package.json/engines
=> Fix renovate configuration for moon's node toolchain

projects/app/public/.well-known/apple-app-site-association
It was taking up too much space on other pages and caused page jank.
=> Only show the iOS Smart App Banner on the home page

.moon/toolchain.yml
This pull request includes a minor change to the `.moon/toolchain.yml` file. The change updates the `yarn` version reference to use the correct package name.
* [`.moon/toolchain.yml`](diffhunk://#diff-9e69e94edf8c6f7a6d5a85bf548d7c646d4b1ffed72d76a6b2a9b5d2f12af21aL5-R5): Updated the `yarn` version reference to `@yarnpkg/cli` to reflect the correct package name.
=> Fix Yarn renovate config for moon

projects/app/eslint.config.mjs, projects/app/src/__tests__/data/marshal.test.ts, projects/app/src/app/dev/ui.tsx, projects/app/src/app/learn/reviews.tsx, projects/app/src/data/generator.ts, projects/app/src/data/marshal.ts, projects/app/src/data/query.ts, projects/app/src/env.ts, projects/app/src/typings/eslint__eslintrc.d.ts, projects/static/src/bin/generateSpeech.ts, tsconfig.base.json
This pull request includes several changes to the ESLint configuration and test files in the project. The most important changes include updates to ESLint rules, improvements in type checking and test cases, and the addition of new utility functions for parsing key paths.
* Disabled the `@typescript-eslint/no-unused-vars` rule due to its buggy behavior when variables are only used as types.
* Disabled the `@typescript-eslint/require-await` rule as it is considered annoying when small functions return a promise.
* Added new imports and utility functions for type checking in `marshal.test.ts`. [[1]](diffhunk://#diff-473bcc9c6988444358d164ec950dd822f946e97e1759531f4e5dca392dc9483eR7-R12) [[2]](diffhunk://#diff-473bcc9c6988444358d164ec950dd822f946e97e1759531f4e5dca392dc9483eR26-R29)
* …
=> Add index scan support to rizzle

package.json, projects/app/package.json, projects/app/src/app/(sidenav)/radical/new/[id].tsx, projects/emails/package.json, projects/lib/package.json, projects/static/package.json, yarn.lock
This pull request includes updates to the `prettier` dependency across multiple `package.json` files to ensure consistency in the code formatting tool version.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12-R12): Updated `prettier` from `^3.4.1` to `^3.4.2`.
* [`projects/app/package.json`](diffhunk://#diff-9ebcf40364ca0b131bfb1e02aa3cade3f1b8c39a09abca94223fd5829223b9f6L93-R93): Updated `prettier` from `^3.4.1` to `^3.4.2`.
* [`projects/emails/package.json`](diffhunk://#diff-bd9105077403a52cd68eff74c3fde6de8b78ce764b2e38ed2b39e0048cbe9c45L12-R12): Updated `prettier` from `^3.4.1` to `^3.4.2`.
* [`projects/lib/package.json`](diffhunk://#diff-e65c095bdffa59d160d94afa4bdce1ea696696b1424f7117d107436e65626d1dL14-R14): …
=> upgrade prettier to 3.4.2

.yarn/patches/replicache-npm-14.2.2-d99f6a2b5c.patch, .yarn/patches/replicache-patch-e568419bdf.patch, projects/app/bin/generateHanziDecomposition.ts, projects/app/package.json, projects/app/src/__tests__/data/marshal.test.ts, projects/app/src/__tests__/dictionary/dictionary.test.ts, projects/app/src/__tests__/util/collections.test.ts, projects/app/src/data/marshal.ts, yarn.lock
This pull request focuses on improving the assertions in the test files by replacing `assert.equal` and `assert.deepEqual` with `assert.strictEqual` and `assert.deepStrictEqual`, respectively. These changes ensure that the tests perform strict equality checks, which can help catch subtle bugs.
* Replaced `assert.equal` with `assert.strictEqual` to enforce strict equality checks. [[1]](diffhunk://#diff-473bcc9c6988444358d164ec950dd822f946e97e1759531f4e5dca392dc9483eL150-R162) [[2]](diffhunk://#diff-473bcc9c6988444358d164ec950dd822f946e97e1759531f4e5dca392dc9483eL195-R207) [[3]](diffhunk://#diff-473bcc9c6988444358d164ec950dd822f946e97e1759531f4e5dca392dc9483eL273-R274) [[4]](diffhunk://#diff-473bcc9c6988444358d164ec950dd822f946e97e1759531f4e5dca392dc9483eL305-R306) …
=> Use strict assertion in tests

projects/app/src/__tests__/data/rizzle.test.ts, projects/app/src/app/learn/hsk1.tsx, projects/app/src/app/learn/radicals.tsx, projects/app/src/app/learn/reviews.tsx, projects/app/src/components/ReplicacheContext.tsx, projects/app/src/data/marshal.ts, projects/app/src/data/query.ts, projects/app/src/data/rizzle.ts, projects/app/src/data/rizzleSchema.ts
This pull request includes several changes aimed at improving the handling and querying of skill states and questions for review in the learning application. The changes involve updates to the Replicache context, query functions, and data types.
* Updated the `ReplicacheContext` to use `RizzleReplicache` with a new alias `Rizzle` and modified the provider to use `r.replicache` instead of `rizzle.replicache`. [[1]](diffhunk://#diff-071215ee77f71b2e672dba7671c458a333683377476bc280350e9b653882d7d9L3-R3) [[2]](diffhunk://#diff-071215ee77f71b2e672dba7671c458a333683377476bc280350e9b653882d7d9L22-R70) [[3]](diffhunk://#diff-071215ee77f71b2e672dba7671c458a333683377476bc280350e9b653882d7d9L54-R86)
* Modified the `questionsForReview` function to accept `Rizzle` as a parameter and updated its usage …
=> Add .literal() .nullable()

.gitignore, projects/app/.gitignore
Pull the gitignore entries up a level so that the root installed `expo-sqlite` build files are ignored too.
=> Try fixing EAS Build

.github/actions/moon-affected/action.yml
It seems like runInCI is not `true` as expected, often it's `affected`.
=> Fix moon-affected Github action

.github/instructions/app.instructions.md, .github/instructions/eslint-rules.instructions.md, .github/instructions/expo-audio-sprites.instructions.md, .github/workflows/pr.yml, .moon/tasks/tag-eslint.yml
Previously using `github.ref` I think created different groups for "approve to run workflows" and "ready for review" events, which meant that if you press Approve workflows and then press Ready for review, it would queue a second PR workflow and wouldn't cancel the first one and you'd have to wait for it to finish.
=> Use a more stable concurrency group for PRs

package.json, projects/mdx/package.json, projects/static/package.json, yarn.config.cjs, yarn.lock
Use @expo/server 0.5.1 locally because it's used in production. Can't upgrade until 0.7.0 becomes the stable version as that's where the Vercel fix is included.
=> dedupe @expo/* packages

.github/workflows/copilot-setup-steps.yml
I'm hoping this improves the LLM's reasoning about errors
=> Turn off Git core.quotepath for copilot agent

.github/workflows/copilot-setup-steps.yml
previously it was doing multiple for `push` and `pull_request` events
=> do not run multiple Copilot Setup Steps checks in PR
